import Work1 from "../../assets/work-1.svg"
import Work2 from "../../assets/work-2.svg"
import Work3 from "../../assets/work-3.svg"
import Work4 from "../../assets/work-4.svg"
import Work5 from "../../assets/work-5.svg"
import Work6 from "../../assets/work-6.svg"

const Menu = [
    {id:1,
    image: Work1,
    title:"mise en page",
    category:"Web",
    link:"https://codepen.io/roronoa-pharell/pen/qBopMJV"},
    {id:2,
    image: Work2,
    title:"Kollision",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1A_dWJQkn03O-1WSmD9nLA2RgMHVyxzFC?usp=share_link"},
    {id:3,
    image: Work3,
    title:"Example card site",
    category:"Web",
    link:"https://codepen.io/roronoa-pharell/pen/xxzeWXX"},
    {id:4,
    image: Work4,
    title:"RPG Java",
    category:"Java",
    link:"https://drive.google.com/drive/folders/1bgA3PY1WfyHpjAfiCscIwI2j91CEmGuE?usp=share_link"},
    {id:5,
    image: Work5,
    title:"React post",
    category:"Web",
    link:"https://codepen.io/roronoa-pharell/pen/WNzpXOG"},
    {id:6,
    image: Work6,
    title:"Barre de recherche",
    category:"Web",
    link:"https://codepen.io/roronoa-pharell/pen/qBoqMXq"},
    {id:7,
    image: Work1,
    title:"Tic Tac Toe",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1Yc53fy9bq-GcQ-V5xfMopWMVn4pz94FX?usp=sharing"},
    {id:8,
    image: Work2,
    title:"Jeu de la vie",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1Yc53fy9bq-GcQ-V5xfMopWMVn4pz94FX?usp=sharing"},
    {id:9,
    image: Work3,
    title:"Pierre feuille ciseaux",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1Yc53fy9bq-GcQ-V5xfMopWMVn4pz94FX?usp=sharing"},
    {id:10,
    image: Work4,
    title:"Jeu de cartes bataille",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1A_dWJQkn03O-1WSmD9nLA2RgMHVyxzFC?usp=share_link"},
    {id:11,
    image: Work5,
    title:"Grille clic exemple",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1Yc53fy9bq-GcQ-V5xfMopWMVn4pz94FX?usp=sharing"},
    {id:12,
    image: Work6,
    title:"Convertiseur de ppm - Python",
    category:"Prochainement",
    link:"#"},
    {id:13,
    image: Work1,
    title:"Visualisation géographique des licence de sport - Python",
    category:"Prochainement",
    link:"#"},
    {id:14,
    image: Work2,
    title:"Calculatrice - Python",
    category:"Prochainement",
    link:"#"},
    {id:15,
    image: Work3,
    title:"Portfolio - React js",
    category:"Web",
    link:"#"},
    {id:16,
    image: Work4,
    title:"Tableau de Bord - html",
    category:"web",
    link:"#"},
    {id:17,
    image: Work4,
    title:"Simple Texte",
    category:"web",
    link:"https://codepen.io/roronoa-pharell/pen/mdxwoog"}
];

export default Menu;