const Data = [
    {id:1,
    category:"education",
    icon:"icon-graduation",
    year: "2022 - maintenant",
    title:"Licence Histoire",
    desc:"Université Paris Est Créteil - Créteil"},
    {id:2,
    category:"education",
    icon:"icon-graduation",
    year: "2021 - 2022",
    title:"Double licence Mathématiques et informatiques ",
    desc:"Université Gustave eiffel  - Champs-sur-marne"},
    {id:3,
    category:"education",
    icon:"icon-graduation",
    year: "2018 - 2021",
    title:"Bacalauréat Mathématiques et Numériques et sciences de l’informatiques",
    desc:"Lycée René Descartes - Champs-sur-marne"},
    {id:4,
    category:"education",
    icon:"icon-graduation",
    year: "2014 - 2018",
    title:"Diplome nationale du Brevet",
    desc:"Collège Jean Wiener - Champs-sur-marne "},
    {id:5,
    category:"experience",
    icon:"icon-briefcase",
    year: "2018 - 2018",
    title:"Stagiaire en restauration",
    desc:"Tablapizza - Noisiel"},
    {id:6,
    category:"",
    icon:"",
    year: "",
    title:"",
    desc:""}
];

export default Data;